package Gun09;

import Utils.BaseStaticDriver;
import org.junit.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;

public class _01_SeleniumProje extends BaseStaticDriver {
    public static void main(String[] args) {
        DriverStart();
        driver.get("http://a.testaddressbook.com/sign_in");
        WebElement email= driver.findElement(By.id("session_email"));
        email.sendKeys("ex@ex.com");
        Wait(2);
        WebElement password= driver.findElement(By.id("session_password"));
        password.sendKeys("1234");
        Wait(2);
        WebElement singIn=driver.findElement(By.name("commit"));
        singIn.click();
        Wait(2);
        WebElement address=driver.findElement(By.xpath("//*[text()='Addresses']"));
        address.click();
        Wait(2);
        WebElement newAddress=driver.findElement(By.xpath("//*[text()='New Address']"));
        newAddress.click();
        Wait(2);
        WebElement firstName= driver.findElement(By.id("address_first_name"));
        firstName.sendKeys("Fernando");
        Wait(2);
        WebElement lastName= driver.findElement(By.id("address_last_name"));
        lastName.sendKeys("Torres");
        Wait(2);
        WebElement address1= driver.findElement(By.id("address_street_address"));
        address1.sendKeys("Anfield Rd");
        Wait(2);
        WebElement address2= driver.findElement(By.id("address_secondary_address"));
        address2.sendKeys("Anfield");
        Wait(2);
        WebElement city= driver.findElement(By.id("address_city"));
        city.sendKeys("Liverpool");
        Wait(2);
        WebElement menu=driver.findElement(By.id("address_state"));
        Select ddmenu=new Select(menu);
        ddmenu.selectByIndex((int)(Math.random()*10));
        Wait(2);
        WebElement zipCode= driver.findElement(By.id("address_zip_code"));
        zipCode.sendKeys("L4 0TH");
        Wait(2);
        WebElement country= driver.findElement(By.id("address_country_us"));
        country.click();
        Wait(2);
        WebElement birthday= driver.findElement(By.id("address_birthday"));
        birthday.sendKeys("03/20/1984");
        Wait(2);
        WebElement age= driver.findElement(By.id("address_age"));
        age.sendKeys("36");
        Wait(2);
        WebElement website= driver.findElement(By.id("address_website"));
        website.sendKeys("https://www.google.com/");
        Wait(2);
        WebElement phone= driver.findElement(By.id("address_phone"));
        phone.sendKeys("8625747878");
        Wait(2);
        WebElement climbing= driver.findElement(By.id("address_interest_climb"));
        climbing.click();
        Wait(2);
        WebElement dancing= driver.findElement(By.id("address_interest_dance"));
        dancing.click();
        Wait(2);
        WebElement note= driver.findElement(By.id("address_note"));
        note.sendKeys("Never Back Down");
        Wait(2);
        WebElement createAddress= driver.findElement(By.name("commit"));
        createAddress.click();
        Wait(2);
        WebElement name2= driver.findElement(By.cssSelector("[data-test='first_name']"));
        Assert.assertTrue( name2.getText().contains("Fernando"));
        Wait(2);
        WebElement lastname= driver.findElement(By.cssSelector("[data-test='last_name']"));
        Assert.assertTrue( lastname.getText().contains("Torres"));
        Wait(2);
        WebElement address3=driver.findElement(By.xpath("//*[text()='Addresses']"));
        address3.click();
        Wait(2);
        WebElement edit=driver.findElement(By.partialLinkText("Edit"));
        edit.click();
        Wait(2);
        WebElement editFirstname=driver.findElement(By.id("address_first_name"));
        editFirstname.clear();
        editFirstname.sendKeys("Peter");
        Wait(2);
        WebElement editLastname=driver.findElement(By.id("address_last_name"));
        editLastname.clear();
        editLastname.sendKeys("Crouch");
        Wait(2);
        WebElement updateAddress=driver.findElement(By.name("commit"));
        updateAddress.click();
        Wait(2);
        WebElement updateName= driver.findElement(By.cssSelector("[data-test='first_name']"));
        Assert.assertTrue( updateName.getText().contains("Peter"));
        Wait(2);
        WebElement updatelastname= driver.findElement(By.cssSelector("[data-test='last_name']"));
        Assert.assertTrue( updatelastname.getText().contains("Crouch"));
        Wait(2);
        WebElement address4=driver.findElement(By.cssSelector("[data-test='addresses']"));
        address4.click();
        Wait(2);
        WebElement destroy=driver.findElement(By.partialLinkText("Destroy"));;
        destroy.click();
        Wait(2);
        driver.switchTo().alert().accept();
        WebElement remove= driver.findElement(By.cssSelector("[class='alert alert-notice']"));
        Assert.assertTrue( remove.getText().contains("Address was successfully destroyed."));


        WaitQuit();

    }
}
